### ISSUE TITLE
Send only basic types to Kingfisher Process

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#329]
Until https://github.com/open-contracting/kingfisher-process/issues/209 is closed, if a data source embeds OCDS data in a new place, we need to add a new data type to Kingfisher Process, and then use that `data_type` in the spider. After that issue is closed, we can just specify e.g. a `root_path` to indicate where the OCDS data is embedded.

~~To avoid the overhead of creating more data types, some spiders index to the OCDS data, and then use `save_data_to_disk` to save just the embedded OCDS data. This isn't ideal, as we're not storing the additional content, which might be relevant.~~

The spiders that do this are:

* [x] honduras_portal_records (avoids a `record_list_in_results` type)
* [x] honduras_portal_releases (avoids `release_list_in_results`)
* [x] mexico_quien_es_quien (avoids `record_package_list_in_data`)
* [x] openopps (avoids `release_package_in_json_in_list_in_results`)

-----

Instead of closing the issue in Process, in https://github.com/open-contracting/kingfisher-collect/issues/329#issuecomment-730846155 and https://github.com/open-contracting/kingfisher-collect/pull/565#discussion_r527157819, I suggest addressing these issues in Collect. The above spiders should configure a `data_pointer` (or `root_path`) and an item pipeline should index to that part of the data.

**Comment by jpmckinney** [comment]
Spiders that use `parse_json_lines` and some spiders that inherit from `ZipSpider` also don't send the full response to Kingfisher Process.

**Comment by jpmckinney** [comment]
Same for `parse_json_array`.

**Comment by jpmckinney** [comment]
Although there has been no discussion in #482, I doubt the data outside the OCDS data is very useful. In any case, Kingfisher Process doesn't know what to do with it, and just discards it (even now). So, I'm changing the definition of this issue to instead do the 'root path' processing within Kingfisher Collect, and to only send OCDS data to Kingfisher Process.

**Comment by yolile** [comment]
Updated list of spiders that don't use record, release, record_package or release_package `data_type`:

- [ ] ArgentinaVialidad `release_package_list`
- [ ] BoliviaAgetic `release_list`
- [ ] ColombiaBulk `release_in_Release`
- [ ] KenyaMakueni `release_package_list`
- [ ] Kosovo `release_list`
- [ ] MexicoAdministracionPublicaFederal `record_package_list_in_results`
- [ ] MexicoQuienEsQuien `record_package_list`
- [ ] OpenOpps `release_package_list`
- [ ] UKContractsFinder `release_package_list_in_results`

**Comment by yolile** [comment]
I'm implementing this using a [Spider Middleware](https://docs.scrapy.org/en/latest/topics/spider-middleware.html) as agreed and it works perfectly. However, I have some questions about how the middleware should handle items:
- For each `File` item the middleware should:
a) Transform the `File` into multiple `FileItems` and keep the original `File` item too, but changing it to `post_to_api =False` (meaning that the original file will be saved into the disk and only the `FileItem` will be sent to `KingfisherProcess`)
b) The same but not keeping the `File` item, resulting in no items saved into the disk and only sending them to `KingfisherProcess`
c) Transform the `File` into multiple `File` items, saving them into disk and sending them to  `KingfisherProcess`

And also, for each list, should the middleware joint the list into a single package with multiple releases/records instead of sending one package/releases/record to `KIngfisherProcess`? If so, we will be sending only release_package or record_package to `KingfisherProcess` and not unpackaged ones?

**Comment by jpmckinney** [comment]
Before closing this issue, we should check how it affects #471, #449, #450.

**Comment by jpmckinney** [comment]
>  BoliviaAgetic release_list

@yolile I don't think root_path needs to be used here?

> c) Transform the File into multiple File items, saving them into disk and sending them to KingfisherProcess

Noting that this is what we went forward with in #572.

> for each list, should the middleware joint the list into a single package with multiple releases/records instead of sending one package/releases/record to KIngfisherProcess?

Noting that #572 creates one FileItem per entry in the list (if the original data is a JSON array of OCDS data), and each is sent to KingfisherProcess separately.

>  If so, we will be sending only release_package or record_package to KingfisherProcess and not unpackaged ones?

Noting that #572 includes a middleware to add a minimal package around a single release/record.

**Comment by yolile** [comment]
> @yolile I don't think root_path needs to be used here?

Not anymore!
