### ISSUE TITLE
Do we want to use CLOSESPIDER_ERRORCOUNT?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#384]
https://docs.scrapy.org/en/latest/topics/extensions.html#closespider-errorcount

By default, Scrapy will try to continue. If our main use case is to collect "clean" and complete collections, we should perhaps set this to 1 in settings.py.

(The CloseSpider extension is enabled by default.)

**Comment by yolile** [comment]
@mrshll1001 @duncandewhurst @romifz what do you think?

**Comment by duncandewhurst** [comment]
I can't recall for which publishers, but I think we have had cases where there are intermittent issues with retrieving data but it has still been useful for us to provide feedback based on an incomplete dataset.

**Comment by romifz** [comment]
I agree with @duncandewhurst.

**Comment by jpmckinney** [comment]
@duncandewhurst @romifz For spiders with known issues, we can have something like `allow_errors = True`. For other spiders, this can default to `False`, but it can be overridden with a spider argument e.g. `scrapy crawl myspider -a allow_errors=true` or:

    curl -n http://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=myspider -d allow_errors=true

To restate the question: Would it be good for spiders that aren't expected to error to stop collecting data when there is an error (which might indicate a bug in the spider rather than an issue in the source)? Or should we always try to collect as much as possible (perhaps because we expect every data source to sometimes have errors)?

**Comment by duncandewhurst** [comment]
I'm mainly thinking about it from the perspective of providing feedback to a new publisher, in which case don't know whether to expect the spider to have errors or not, so I'd lean towards the latter.

**Comment by romifz** [comment]
I feel like stopping the scraper after a single error would add an extra task for the analyst that may not be necessary. 

Let's say that I start a spider that worked with no issues until now. The spider finds a few 500 errors, but most of the requests are successful.

If the spider continues after finding errors I would notice them in the log summary, and if the errors are not too many, I would take note of them and continue with the analysis.

If the spider stops after the first error, I would have to test some of the URLs to see if there is an issue with the source, and if I think that the errors are in some URLs only, I have to rerun the spider with the `allow_errors` parameter.

 > (which might indicate a bug in the spider rather than an issue in the source)

I would rather expect that the publisher is modifying their publication or working on their servers (that may happen in active developments like the Honduras open contracting portal).

However, I understand that we don't what a spider running to return errors only. I think that, instead of stopping at the first error, we should wait for a significant number of consecutive errors, or a timeframe with no successful responses (like 10-20 requests, or a full minute). Spiders that make a low number of requests may not need to stop after errors.

**Comment by jpmckinney** [comment]
Makes sense – OCDS APIs are not as reliable as, for example, the GitHub API, so we need to tolerate more errors.

I'm happy to close this issue and instead work on making it easier to analyze the log files #198.
