### ISSUE TITLE
Check Mexico scrapers

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#391]
- `mexico_cdmx` timeout
- `mexico_grupo_aeroporto` (no sample)
- `mexico_inai`  (no sample)
- `mexico_jalisco` 404 error

**Comment by jpmckinney** [comment]
* http://www.contratosabiertos.cdmx.gob.mx is not responding
* https://contratacionesabiertas.jalisco.gob.mx has a maintenance page. not sure if it is coming back. We can create a CRM ticket and assign it to Nico. (Also, ask Nico to create a GitHub user so we can tag him in future.)

For the ones without samples, I think they should be covered in #84 instead of this issue.

**Comment by jpmckinney** [comment]
Can you also ask Nico about CDMX? I created a separate issue for Jalisco: #402

**Comment by aguilerapy** [comment]
`mexico_cdmx` discontinued, CRM issue: https://crm.open-contracting.org/issues/6034.

**Comment by jpmckinney** [comment]
Hmm, doesn't the end of the update say they will look into re-enabling it? (for consultation, even if they don't intend to update it)

**Comment by aguilerapy** [comment]
They say the platform is deprecated, it only had around 200 contracts records from a previous administration, including an extinct institution, in the end they only said that they were going to check the server where it was hosted. Do you want to remove it from blocked?

**Comment by jpmckinney** [comment]
Let's remove it from blocked and just delete the spider. I don't imagine anyone will miss it (if it ever comes back).
