### ISSUE TITLE
Add spider for new Portugal API

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-collect#439]
**Links to bulk download and/or API documentation**
https://www.base.gov.pt/swagger/index.html

**Link to CRM issue**
https://crm.open-contracting.org/issues/6093

**Priority**
TBD 

cc @mrshll1001

**Comment by aguilerapy** [comment]
Trying to access the API gives us `twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]`

The connection to https://www.base.gov.pt/api/Record/GetRecords?offset=1 is encrypted and authenticated using TLS 1.0 (obsolete), RSA (obsolete), and 3DES_EDE_CBC (obsolete) with HMAC-SHA1, see https://www.ssllabs.com/ssltest/analyze.html?d=www.base.gov.pt. 

So the cipher used is TLS_RSA_WITH_3DES_EDE_CBC_SHA ([DES-CBC3-SHA](https://www.openssl.org/docs/man1.0.2/man1/ciphers.html#TLS-v1.0-cipher-suites) shorter) and I tryied to force the Scrapy settings with [DOWNLOADER_CLIENT_TLS_CIPHERS](https://docs.scrapy.org/en/latest/topics/settings.html#std-setting-DOWNLOADER_CLIENT_TLS_CIPHERS) and [DOWNLOADER_CLIENT_TLS_METHOD](https://docs.scrapy.org/en/latest/topics/settings.html#downloader-client-tls-method) but it didn't work due to an unusable ciphers error.

Some forums mention that this is can be resolved by lowering the version in `cryptography<2`, but it generates incompatibility with `scrapy 1.8.0` and other packages.

Here they mention that the curl command works, but it didn't give me any results either https://crm.open-contracting.org/issues/6093#note-1.

May I ask if you know of any solutions? @jpmckinney

**Comment by yolile** [comment]
it does'nt work with curl:

`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.base.gov.pt:443`

or requests either:

`urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))`

and the browser complains about the "non-secure" issue. I think we should tell the publisher that they need to fix the security issues or use http.

**Comment by jpmckinney** [comment]
> Some forums mention that this can be resolved by lowering the version in cryptography<2, but it generates incompatibility with scrapy 1.8.0 and other packages.

* https://stackoverflow.com/questions/45924568/scrapy-twisted-connection-lost-in-non-clean-fashion-no-proxy-already-tried-hea
* https://github.com/scrapy/scrapy/issues/2311
* https://github.com/scrapy/scrapy/issues/2717
* https://github.com/scrapy/scrapy/issues/2916
* https://github.com/scrapy/scrapy/issues/3065
* https://github.com/scrapy/scrapy/issues/3103
* https://github.com/scrapy/scrapy/issues/4423
* https://github.com/scrapy/scrapy/issues/4582

I looked into it, and I think I might have to install OpenSSL with SSLv3 enabled (it's disabled by default by Homebrew, and I'm not sure if there's an easy way to enable it). However, SSLv3 is dead, e.g. https://github.com/Homebrew/legacy-homebrew/issues/34634 Otherwise, I tried copying the request as cURL from Chrome and then pasting into https://michael-shub.github.io/curl2scrapy/, just in case the issue wasn't related to SSL.

**Comment by Urahara** [comment]
> > Some forums mention that this can be resolved by lowering the version in cryptography<2, but it generates incompatibility with scrapy 1.8.0 and other packages.
> 
> * https://stackoverflow.com/questions/45924568/scrapy-twisted-connection-lost-in-non-clean-fashion-no-proxy-already-tried-hea
> * [scrapy/scrapy#2311](https://github.com/scrapy/scrapy/issues/2311)
> * [scrapy/scrapy#2717](https://github.com/scrapy/scrapy/issues/2717)
> * [scrapy/scrapy#2916](https://github.com/scrapy/scrapy/issues/2916)
> * [scrapy/scrapy#3065](https://github.com/scrapy/scrapy/issues/3065)
> * [scrapy/scrapy#3103](https://github.com/scrapy/scrapy/issues/3103)
> * [scrapy/scrapy#4423](https://github.com/scrapy/scrapy/issues/4423)
> * [scrapy/scrapy#4582](https://github.com/scrapy/scrapy/issues/4582)
> 
> I looked into it, and I think I might have to install OpenSSL with SSLv3 enabled (it's disabled by default by Homebrew, and I'm not sure if there's an easy way to enable it). However, SSLv3 is dead, e.g. [Homebrew/legacy-homebrew#34634](https://github.com/Homebrew/legacy-homebrew/issues/34634) Otherwise, I tried copying the request as cURL from Chrome and then pasting into https://michael-shub.github.io/curl2scrapy/, just in case the issue wasn't related to SSL.

https://github.com/okfn-brasil/diario-oficial/issues/176#issuecomment-661043809 Can you test with this Dockerfile?

**Comment by jpmckinney** [comment]
This is now unblocked. We can just use HTTP instead of HTTPS. (CRM-6093)
