### ISSUE TITLE
Digiwhist spiders: consider one spider with filters

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#710]
eg one spider (`europe_digiwhist`) with one country filter from https://opentender.eu/download eg (`scrapy crawl europe_digiwhist -a country=austria`)

**Comment by jpmckinney** [comment]
Noting that, for the data registry backend, we will need to store both the spider name and the list of arguments, since users typically want specific countries, not all of Europe.

And in Kingfisher Process, the input arguments are not yet stored (#411), so for now the note will have to be clear which country was filtered.

**Comment by yolile** [comment]
I will close this as there is no demand for this, and the registry is also working well as it is.
