### ISSUE TITLE
Allow people to resume scrapers that have experienced intermittent errors 

### ISSUE THREAD

**Issue by ghost** [open-contracting/kingfisher-collect#79]
Old title: Armenia download died after downloading 2316 files with a generic ["Connection error"] error.

Found during #100 work

The URL - https://armeps.am/ocds/release?limit=100&offset=1519400579553 - opens fine in a browser -  maybe just a temp glitch?

**Comment by jpmckinney** [comment]
@odscjames @yolile With Scrapy, is it possible to resume scrapers that have experienced intermittent errors, or is this still an issue that needs to be resolved?

**Comment by odscjames** [comment]
The use case here is runs that have errors, and we try again in a day or something similar to see if those errors have cleared. 

We would need to look into how that would work with Scrapy - this isn't something that works currently.

Some of our spiders do manually do things around this - https://github.com/open-contracting/kingfisher-scrape/blob/master/kingfisher_scrapy/spiders/colombia.py#L32 - but we should look into this.

**Comment by jpmckinney** [comment]
Assuming the source has a publication pattern that allows resuming:

If the source takes a long time to collect or contains a lot of data, another use case for resuming is to get any new releases since the last collection. This is relevant to a (non-helpdesk) data analyst who is working with the same source(s) over long periods of time and/or at frequent intervals (e.g. daily), and who doesn't want or can't store multiple copies of the same data.

This makes a critical assumption: old releases aren't changed or deleted (this is required by the standard, but a source can be nonconformant).

If a second assumption holds – that only new releases (i.e. those with a more recent `date`) are added over time – then instead of re-compiling *all* releases, the previously compiled releases can simply be updated with the new releases (this can be done by putting the compiled release as the first release in the list).

**Comment by jpmckinney** [comment]
Some relevant Scrapy docs: https://docs.scrapy.org/en/latest/topics/jobs.html

Can also look into how the following maintain state:

* https://github.com/my8100/scrapydweb
* https://github.com/scrapy/scrapyd/pull/359
* https://github.com/my8100/scrapydweb/issues/21
* https://github.com/my8100/scrapydweb/blob/2df1c3d5dcf92dd1a8b11eb5cf52663afb751316/scrapydweb/views/dashboard/jobs.py
