### ISSUE TITLE
Italy: Parse JSON instead of HTML

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#822]
The page requests this document: https://www.appaltipop.it/_next/data/LxpUO4Pg-S_nnq33fzaED/it/tenders.json

**Comment by jpmckinney** [comment]
Looking at this URL, I'm not sure if it's permanent, or if it's generated whenever the page is re-built.

**Comment by jpmckinney** [comment]
> Looking at this URL, I'm not sure if it's permanent, or if it's generated whenever the page is re-built.

@yolile Isn't this a problem? (They aren't updating the data, so it's not *currently* a problem.)

**Comment by yolile** [comment]
It is hard to know how they are generating that URL, it seems to be permanent as it is the same. However, I just saw on their page that they have an [API](https://www.appaltipop.it/api/v1/#/Buyers/get_buyers), and we can use https://www.appaltipop.it/api/v1/buyers instead of https://www.appaltipop.it/_next/data/LxpUO4Pg-S_nnq33fzaED/it/tenders.json to be 100% sure to always get the files list. Another option is to use the GitHub API similar to #821

**Comment by Ravf95** [comment]
I think it's a good idea use only the [API endpoint](https://www.appaltipop.it/api/v1/buyers) to list the files, then we can't download some wrong file.
