### ISSUE TITLE
Check Armenia scraper

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#86]
The old scraper has not been tested according to open-contracting/kingfisher#100

**Comment by aguilerapy** [comment]
Running the Armenia scraper, the last page saved is https://armeps.am/ocds/release?limit=100&offset=1519411907725 , then, in the [next request page](https://armeps.am/ocds/release?limit=100&offset=1519716611092) return error 500 and finish the spider.

**Comment by jpmckinney** [comment]
I think the action here is to document the limitations of the API (e.g. give an indication of how many pages of results get downloaded before the 500 error occurs).

**Comment by aguilerapy** [comment]
So I will write the scraper and show the message of how much was downloaded when reaching the error 505, right? @jpmckinney

**Comment by jpmckinney** [comment]
The spider runs – it just errors at some point (and we have no way to skip the bad page).

So, the action is to describe in the docstring about how many pages/results can be downloaded before the error occurs, e.g.

> The API consistently returns an irrecoverable error at ``offset=1519828326255``, after downloading about 120 pages (as of 2020-06-24).

**Comment by jpmckinney** [comment]
Actually, that gave me an idea to get around the bug: we can just increase the timestamp until it starts working again. The lowest number I got was https://armeps.am/ocds/release?limit=100&offset=1519840056264

**Comment by aguilerapy** [comment]
How does that manual binary search work? 

There could be another available `offset` between [1519828326255](https://armeps.am/ocds/release?limit=100&offset=1519411907725 ) and [1519840056264](https://armeps.am/ocds/release?limit=100&offset=1519840056264), right?

**Comment by jpmckinney** [comment]
I took the last number that worked (1519411907725) as the minimum and and picked a number in the future as the maximum, then took the midpoint between them. If it worked, I set the midpoint to the maximum; otherwise, I set it to the minimum. Then did it all again.

It's possible that there are some numbers in between that work, but this is unlikely – and the only way to check is to advance the offset some small increment at a time, which will require a lot of failing requests.

**Comment by aguilerapy** [comment]
How do you picked that number in the future as the maximum? Because that number directly influences what offsets we reach. For example if the maximum picked is `a`, the midpoint reached is `x`, on the other hand, if the maximum picked is `b`, the midpoint is `y`.

If the midpoint stops moving and the current `offset` doesn't work, do we continue from the last point that worked?

And what happens if we don't find any `offset` that works during the search? @jpmckinney

**Comment by jpmckinney** [comment]
Good questions! I think we will have to test. But here's one approach:

1. Start with a maximum that is one day in the future (offset is in microseconds).
1. If it succeeds, do a binary search to find the lowest offset that works. (We accept the assumption that there aren't multiple periods within that day that error.)
1. If it errors, assume that all intervening offsets would also error. Set the minimum to the maximum, and advance the maximum by one day.
1. If it errors for 5 (10?) consecutive days, don't send any more requests (assume there are no further good offsets).

**Comment by aguilerapy** [comment]
Running the Armenia scraper now, we reach a different first page error with 1519405680727 (not 1519411907725). 

Starting the search with the mentioned approach in https://armeps.am/ocds/release?limit=100&offset=1519405680727 the maximum that is one day in the future is https://armeps.am/ocds/release?limit=100&offset=1519492080727 returning error, thus we lose the page https://armeps.am/ocds/release?limit=100&offset=1519411907725 (old offset that we found weeks before) by assuming that all intervening offsets would also error.

The API itself skips this page https://armeps.am/ocds/release?limit=100&offset=1519411907725 because the next_page in https://armeps.am/ocds/release?limit=100&offset=1519405680727 is https://armeps.am/ocds/release?limit=100&offset=1519411911952 (4227 microseconds of difference).

Anyway, I think the criteria works well and finds correctly https://armeps.am/ocds/release?limit=100&offset=1519840056264 (the lowest number you got using a manual binary search).

**Comment by yolile** [comment]
closed by #442
