### ISSUE TITLE
Add a message to explicitly state output location at the end of a crawl

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-collect#937]
Related to CRM-8186

A user was unable to intuit where the downloaded data was following a crawl. At the conclusion of successful crawls, we could output a message with the location.

I think it would be sufficient to state only the path relative to the user's working directory when running the scrapy command e.g. `Data is stored in a folder called "data" beneath where you ran the scrapy command`, however we could also consider the absolute path to be very explicit (I'm not a fan of this; this could get very long).

**Comment by jpmckinney** [comment]
I think that will work. Makes sense for the message to come from that extension, since it is the one writing the files.

Be sure to test where the new message appears in the output. Scrapy's core is responsible for printing the crawl statistics (in `ExecutionEngine.close_spider()`), so its position might be hard to set.

We could disable statistics with `STATS_DUMP = False` or better `STATS_DUMP = 'KINGFISHER_STATS_DUMP' in os.environ`

**Comment by Ravf95** [comment]
Yes, that's great, we can also document the new environment variable in #936

**Comment by jpmckinney** [comment]
Re: `STATS_DUMP`, see https://github.com/open-contracting/kingfisher-collect/pull/956 as to why it wasn't implemented.
