### ISSUE TITLE
Limit the number of FileItem with spider middlewares

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#942]
@jpmckinney 

From https://github.com/open-contracting/kingfisher-collect/pull/940#pullrequestreview-992316521:

> This might be better as a spider middleware. I think some other sources that use root_path (with item somewhere in the root path) suffer from the same design issue, like OpenOpps.
>
> Although Process v2 can handle it, sending millions more RabbitMQ messages than necessary is still slower than performing a bit of aggregation in Collect.

and https://github.com/open-contracting/kingfisher-collect/pull/940#issuecomment-1143909378:

> As I think about it more, maybe if 'item' in root_path.split('.'):, and if the data_type is release_package or record_package, then RootPathMiddleware should always combine the packages.

@yolile

> Yes, I thought about updating RootPathMiddleware so we apply the same solution for the cases you mentioned. I can change the middleware to do that if you are happy with that.

> We could do the same for line delimiter files, for example, Digiwhist, although we will need to limit the number of releases per package (for big files), similar to `ResizePackageMiddleware`. And we could do the same for releases and records, but adding them to an empty package first, as in `AddPackageMiddleware`

**Comment by jpmckinney** [comment]
To limit the scope of the middleware, the modifications to the data should be limited to fixing known data publication anti-patterns, which are:

* multiple packages in a single file: combine the packages
* a JSON array of individual releases/records without a package: wrap the array in an empty package

We can leave line-delimited files alone for now, because that format is appropriate for streaming of large files. The line-delimited format is not currently being misused.

The matches for `root_path.*\bitem\b` are:

* release_package
  * argentina_vialidad (item)
  * ecuador_sercop_bulk (item)
  * kenya_makueni (item)
  * mexico_administracion_publica_federal_bulk (item)
  * MexicoINAIBase (arrayReleasePackage.item)
  * openopps (results.item.json)
* record_package
  * mexico_administracion_publica_federal_api (results.item)
* release
  * argentina_buenos_aires (main.item)
  * mexico_plataforma_digital_nacional (item)
  * mexico_quien_es_quien_releases (data.item)
